apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-internal-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-internal
    spec:
      containers:
      - name: helloworld-internal
        image: kumar.azurecr.io/helloworld
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "services"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30304
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: helloworld-internal
