apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynodeapp-internal-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mynodeapp-internal
    spec:
      containers:
      - name: mynodeapp-internal
        image: kumar.azurecr.io/mynodeapp
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: mynodeapp-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "services"
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30300
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mynodeapp-internal
