apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynodeapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: kumar.azurecr.io/mynodeapp
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: mynodeapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30303
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mynodeapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mynodeapp-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /mynodeapp
        backend:
          serviceName: mynodeapp
          servicePort: http
