apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: samplenodeapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: samplenodeapp-v1
    spec:
      containers:
      - name: k8s-demo
        image: kumar.azurecr.io/samplenodeapp
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: samplenodeapp-v1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30303
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: samplenodeapp-v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: samplenodeapp-v1-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /v1
        backend:
          serviceName: samplenodeapp-v1
          servicePort: http
